/*
 * Generated by gdbus-codegen 2.46.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __NOTIFICATIONS_H__
#define __NOTIFICATIONS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.Notifications */

#define TYPE_NOTIFICATIONS (notifications_get_type ())
#define NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_NOTIFICATIONS, Notifications))
#define IS_NOTIFICATIONS(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_NOTIFICATIONS))
#define NOTIFICATIONS_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_NOTIFICATIONS, NotificationsIface))

struct _Notifications;
typedef struct _Notifications Notifications;
typedef struct _NotificationsIface NotificationsIface;

struct _NotificationsIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_close_notification) (
    Notifications *object,
    GDBusMethodInvocation *invocation,
    guint arg_id);

  gboolean (*handle_get_capabilities) (
    Notifications *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_get_server_information) (
    Notifications *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_notify) (
    Notifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout);

  void (*action_invoked) (
    Notifications *object,
    guint arg_id,
    const gchar *arg_action_key);

  void (*notification_closed) (
    Notifications *object,
    guint arg_id,
    guint arg_reason);

};

GType notifications_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *notifications_interface_info (void);
guint notifications_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void notifications_complete_get_capabilities (
    Notifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *capabilities);

void notifications_complete_notify (
    Notifications *object,
    GDBusMethodInvocation *invocation,
    guint id);

void notifications_complete_close_notification (
    Notifications *object,
    GDBusMethodInvocation *invocation);

void notifications_complete_get_server_information (
    Notifications *object,
    GDBusMethodInvocation *invocation,
    const gchar *name,
    const gchar *vendor,
    const gchar *version,
    const gchar *spec_version);



/* D-Bus signal emissions functions: */
void notifications_emit_notification_closed (
    Notifications *object,
    guint arg_id,
    guint arg_reason);

void notifications_emit_action_invoked (
    Notifications *object,
    guint arg_id,
    const gchar *arg_action_key);



/* D-Bus method calls: */
void notifications_call_get_capabilities (
    Notifications *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean notifications_call_get_capabilities_finish (
    Notifications *proxy,
    gchar ***out_capabilities,
    GAsyncResult *res,
    GError **error);

gboolean notifications_call_get_capabilities_sync (
    Notifications *proxy,
    gchar ***out_capabilities,
    GCancellable *cancellable,
    GError **error);

void notifications_call_notify (
    Notifications *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean notifications_call_notify_finish (
    Notifications *proxy,
    guint *out_id,
    GAsyncResult *res,
    GError **error);

gboolean notifications_call_notify_sync (
    Notifications *proxy,
    const gchar *arg_app_name,
    guint arg_replaces_id,
    const gchar *arg_app_icon,
    const gchar *arg_summary,
    const gchar *arg_body,
    const gchar *const *arg_actions,
    GVariant *arg_hints,
    gint arg_expire_timeout,
    guint *out_id,
    GCancellable *cancellable,
    GError **error);

void notifications_call_close_notification (
    Notifications *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean notifications_call_close_notification_finish (
    Notifications *proxy,
    GAsyncResult *res,
    GError **error);

gboolean notifications_call_close_notification_sync (
    Notifications *proxy,
    guint arg_id,
    GCancellable *cancellable,
    GError **error);

void notifications_call_get_server_information (
    Notifications *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean notifications_call_get_server_information_finish (
    Notifications *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GAsyncResult *res,
    GError **error);

gboolean notifications_call_get_server_information_sync (
    Notifications *proxy,
    gchar **out_name,
    gchar **out_vendor,
    gchar **out_version,
    gchar **out_spec_version,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_NOTIFICATIONS_PROXY (notifications_proxy_get_type ())
#define NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_NOTIFICATIONS_PROXY, NotificationsProxy))
#define NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_NOTIFICATIONS_PROXY, NotificationsProxyClass))
#define NOTIFICATIONS_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_NOTIFICATIONS_PROXY, NotificationsProxyClass))
#define IS_NOTIFICATIONS_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_NOTIFICATIONS_PROXY))
#define IS_NOTIFICATIONS_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_NOTIFICATIONS_PROXY))

typedef struct _NotificationsProxy NotificationsProxy;
typedef struct _NotificationsProxyClass NotificationsProxyClass;
typedef struct _NotificationsProxyPrivate NotificationsProxyPrivate;

struct _NotificationsProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NotificationsProxyPrivate *priv;
};

struct _NotificationsProxyClass
{
  GDBusProxyClass parent_class;
};

GType notifications_proxy_get_type (void) G_GNUC_CONST;

void notifications_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Notifications *notifications_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
Notifications *notifications_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void notifications_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
Notifications *notifications_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
Notifications *notifications_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_NOTIFICATIONS_SKELETON (notifications_skeleton_get_type ())
#define NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_NOTIFICATIONS_SKELETON, NotificationsSkeleton))
#define NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_NOTIFICATIONS_SKELETON, NotificationsSkeletonClass))
#define NOTIFICATIONS_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_NOTIFICATIONS_SKELETON, NotificationsSkeletonClass))
#define IS_NOTIFICATIONS_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_NOTIFICATIONS_SKELETON))
#define IS_NOTIFICATIONS_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_NOTIFICATIONS_SKELETON))

typedef struct _NotificationsSkeleton NotificationsSkeleton;
typedef struct _NotificationsSkeletonClass NotificationsSkeletonClass;
typedef struct _NotificationsSkeletonPrivate NotificationsSkeletonPrivate;

struct _NotificationsSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NotificationsSkeletonPrivate *priv;
};

struct _NotificationsSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType notifications_skeleton_get_type (void) G_GNUC_CONST;

Notifications *notifications_skeleton_new (void);


G_END_DECLS

#endif /* __NOTIFICATIONS_H__ */
